#ifndef EVENT_H
#define EVENT_H

enum {
    COUNTER_CPU_CYCLES,
    COUNTER_REF_CPU_CYCLES,
    COUNTER_INSTRUCTIONS,
    COUNTER_CACHE_ACCESSES,
    COUNTER_CACHE_MISSES,
    COUNTER_L1_CACHE_MISSES,
    COUNTER_BRANCH_INSTRUCTIONS,
    COUNTER_BRANCH_MISPREDICTIONS,
    COUNTER_PAGE_FAULTS,
    COUNTER_CPU_CLOCK_NS,
    COUNTER_TASK_CLOCK_NS,
    COUNTER_ALIGNMENT_FAULTS,
    NUMBER_OF_COUNTERS,
};

extern const char *counter_names[NUMBER_OF_COUNTERS];

#endif
