#include "../include/include.h"

const char *metric_names[NUMBER_OF_METRICS] = {
    [METRIC_CPU_CYCLES]            = "METRIC_CPU_CYCLES",
    [METRIC_INSTRUCTIONS]          = "METRIC_INSTRUCTIONS",
    [METRIC_CACHE_ACCESSES]        = "METRIC_CACHE_ACCESSES",
    [METRIC_CACHE_MISSES]          = "METRIC_CACHE_MISSES",
    [METRIC_L1_CACHE_MISSES]       = "METRIC_L1_CACHE_MISSES",
    [METRIC_BRANCH_INSTRUCTIONS]   = "METRIC_BRANCH_INSTRUCTIONS",
    [METRIC_BRANCH_MISPREDICTIONS] = "METRIC_BRANCH_MISPREDICTIONS",
    [METRIC_PAGE_FAULTS]           = "METRIC_PAGE_FAULTS",
    [METRIC_CPU_CLOCK_NS]          = "METRIC_CPU_CLOCK_NS",
    [METRIC_TASK_CLOCK_NS]         = "METRIC_TASK_CLOCK_NS",
    [METRIC_ALIGNMENT_FAULTS]      = "METRIC_ALIGNMENT_FAULTS",
};
